import { Context, Next } from "koa";
import Errors from '../exception'

const catchError = () => async (ctx: Context, next: Next) => {
  try {
    await next();
    if (ctx.status === 404) {
      throw new Errors.NotFound("æœªæ‰¾åˆ°è¯¥è·¯ç”±", 404);
    }
  } catch (err) {
    console.error('ðŸ•· -------->', err);
    if (err.errorCode) {
      // å¦‚æžœæ˜¯è‡ªå·±ä¸»åŠ¨æŠ›å‡ºçš„ HttpExceptionç±» é”™è¯¯
      ctx.status = err.status || err.code || 500;
      ctx.body = {
        code: err.code,
        message: err.message,
        errorCode: err.errorCode,
        request: `${ctx.method} ${ctx.path}`,
      };
    } else {
      ctx.app.emit("error", err, ctx);
    }
  }
};

export default catchError